#!/bin/sh

module="cipher"
device="cipher"
mode="664"

# Group: since distributions do it differently, look for wheel or use staff.
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

# Invoke insmod with all provided arguments. Use a pathname, as insmod doesn't
# look in . by default.
/sbin/insmod ./$module.ko $* || exit 1

# Retrieve the device major number.
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

# Remove stale nodes and replace them, then give gid and perms.

# Usually a load script is shorter; cipher just has a lot of associated devices.

rm -f /dev/${device}[0-8]
for i in 0 1 2 3 4 5 6 7 8 ; do
	mknod /dev/${device}${i} c $major ${i}
done
ln -sf ${device}0 /dev/${device}
chgrp $group /dev/${device}[0-8] 
chmod $mode  /dev/${device}[0-8]

